### ISSUE TITLE
No module name Growl

### ISSUE THREAD

**Issue by scuba323** [sorin-ionescu/weechat-growl#12]
When I load the script, I get this.

python: stdout/stderr: ImportError: No module named Growl

I did pip install gntp already. What is this caused from?

**Comment by sorin-ionescu** [comment]
It can't find it. Where have you installed it?

**Comment by scuba323** [comment]
where did I install the PIP?

EDIT: /usr/local/lib/python2.7/dist-packages

**Comment by lazybensch** [comment]
@scuba323 you might have accidentally installed [gnotify](https://weechat.org/scripts/source/gnotify.py.html/) instead of [growl](https://weechat.org/scripts/source/growl.py.html/). gnotify depends on Growl module
