### ISSUE TITLE
None found when expecting String or Buffer

### ISSUE THREAD

**Issue by whaley** [sorin-ionescu/weechat-growl#2]
I just setup the latest version of growl.py for weechat and I get the following each a grown notification should be triggered (e.g. a nick highlight)

10:45:12       weechat     | growl: coercing to Unicode: need string or buffer, NoneType found

I'm using WeeChat 0.3.5 and Python 2.7.1.

**Comment by sorin-ionescu** [comment]
Make sure weechat is using Unicode.

**Comment by whaley** [comment]
seems the charset plugin isn't installed for me for weechat.  I installed from homebrew so apparently something was missing there.  I think that's the source of my utf problem.

**Comment by sorin-ionescu** [comment]
I also installed via Homebrew since I was not aware of binaries present elsewhere.

**Comment by nicksergeant** [comment]
I'm having this same issue but can't figure out how to fix. Whaley, were you able to fix?

**Comment by sorin-ionescu** [comment]
I think that it's related to the charset. Make sure that your shell is configured properly and that WeeChat is [using](http://www.weechat.org/files/doc/weechat_faq.en.html#charset) unicode.

```
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'
export LC_COLLATE='en_US.UTF-8'
export LC_CTYPE='en_US.UTF-8'
export LC_MESSAGES='en_US.UTF-8'
export LC_MONETARY='en_US.UTF-8'
export LC_NUMERIC='en_US.UTF-8'
export LC_TIME='en_US.UTF-8'
export LESSCHARSET='UTF-8'
```

Have you got plugins enabled that may mess with the WeeChat charset?

A stack trace would be helpful.

**Comment by nicksergeant** [comment]
My lang env's are good, but I think the problem is WeeChat does not have the "Charset" plugin (as indicated here: http://www.weechat.org/files/doc/weechat_faq.en.html#charset). I built via homebrew and running '/plugin' doesn't show Charset as being installed after a fresh install...

**Comment by sorin-ionescu** [comment]
I just checked. I do not have the charset plugin. I do not experience this problem. Send @sjl a message. Ask him if his nick Growl notification pops up.

**Comment by nicksergeant** [comment]
Hmm, really weird. I did talk to him about it, he doesn't have the plugin, either, and has no problems. He runs WeeChat through dvtm, not sure if that would make a difference or not.

**Comment by sorin-ionescu** [comment]
Without a stack trace, it's hard to figure out from where this error is being thrown.

**Comment by nicksergeant** [comment]
I get the error right when loading WeeChat:

https://gist.github.com/63ccf7ef262ef3b12ddd

Any way I could retrieve the stacktrace?

**Comment by nicksergeant** [comment]
As whaley, I also get it whenever the notification should fire.

**Comment by ibtaylor** [comment]
Any news on this? I'm having this problem too.
