### ISSUE TITLE
Not working with growl 1.1.3 on Lion

### ISSUE THREAD

**Issue by artkrz** [sorin-ionescu/weechat-growl#4]
I'm getting weechat     | growl: [Errno 111] Connection refused

can you help ?

**Comment by sorin-ionescu** [comment]
Your Growl version is tool old. It works with 1.3.x, not 1.1.x.

**Comment by artkrz** [comment]
That was a typo. I'm running growl 1.3.3 and weechat on ubuntu in screen session via terminal.

**Comment by sorin-ionescu** [comment]
You have to enable network Growl in Growl's settings. Set the credentials accordingly.

**Comment by artkrz** [comment]
I did, and I was able to telnet to port 23053 TCP. Is there a way to debug this ?

**Comment by sorin-ionescu** [comment]
I do not use it remotely; so, it has not been as debugged as I would like.

The Python GNTP library is pretty basic and buggy.

Can you remotely connect to growl via the command line growlnotifier?

The best way to debug this is to pepper the script with print statements.

**Comment by artkrz** [comment]
I really think something is wrong with the script. I'm able to send notifications using http://search.cpan.org/~mattn/Growl-GNTP-0.10/lib/Growl/GNTP.pm.

**Comment by sorin-ionescu** [comment]
That's the Perl GNTP library, which has its own issues. I was speaking of the Python [GNTP](http://pypi.python.org/pypi/gntp) library. The only way to debug it is to pepper the script with print statements.

**Comment by artkrz** [comment]
I figured this out. So changes to settings in the script will not work as weechat stores settings in plugins.conf and it was reading wrong IP out of there, even though I've changed it in the script code.
