### ISSUE TITLE
Errorno 61 Connection refused

### ISSUE THREAD

**Issue by greenmang0** [sorin-ionescu/weechat-growl#5]
I am using Mountain Lion 10.8.2. 
Getting following error

`growl: [Errno 61] Connection refused`

Growl Version 1.2.2

**Comment by sorin-ionescu** [comment]
Have you updated your Python Growl bindings?

**Comment by greenmang0** [comment]
Thanks for the reply. How am I suppose to do that?

**Comment by sorin-ionescu** [comment]
`pip install --upgrade gntp` is how you upgrade it.

**Comment by greenmang0** [comment]
It says `Requirement already up-to-date: gntp in /Library/Python/2.7/site-packages`

**Comment by sorin-ionescu** [comment]
Is network notification enabled in Growl?

**Comment by greenmang0** [comment]
Yes, It is enabled.

**Comment by rbelouin** [comment]
I get the same problem (growl: [Errno 61] Connection refused):
- Mac OS X 10.7.5
- Growl 1.2
- weechat installed with python support
- gntp installed
- Network: listening for incoming notifications

**Comment by sorin-ionescu** [comment]
Perhaps the GNTP library is not compatible with your Growl version.

**Comment by rbelouin** [comment]
First problem: the plugins try to connect on port 23053 while Growl seems to listen on port 23052. But even if I try ton connect on port 23052, an exception is thrown in growl_notifier library.
Could you tell me with which versions of Mac OS / Growl / gntp are you using weechat-growl?

**Comment by sorin-ionescu** [comment]
I have not used WeChat in a long time.
