### ISSUE TITLE
no handlers for logger "gntp.notifier"

### ISSUE THREAD

**Issue by ewilliam** [sorin-ionescu/weechat-growl#7]
keeping having python related errors. google says to try logging.basicConfig() but i dont know python & efforts to put this somewhere were unsuccessful.

![error screenshot](http://d1zjcuqflbd5k.cloudfront.net/files/acc_55771/D6WJ?response-content-disposition=inline;%20filename=Screenshot%20on%202013-06-13%20at%2012.44.26.png;%20filename*=UTF-8%27%27Screenshot%20on%202013-06-13%20at%2012.44.26.png&Expires=1371152763&Signature=bgfGGEqWCDvrtbqKl9werHdS0BO28AZZeUjYDSGQSGWhep0sc0t9JytX1GID8IUnjYTq94FQMXRXR2pz5qVG1gweOM27MEIXu-lV4C5dpogpm2I2vd6kzRO3IxiP~DdEKzvrEDmKeLMhNnwx-KAQA2SwnwVZae3wKDAWnYpftOg_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)

**Comment by sorin-ionescu** [comment]
It probably needs the following:

``` python
import logging
logging.basicConfig(level=logging.ERROR)
```

**Comment by ewilliam** [comment]
like this? results in the screeenshot

``` python
try:
    import re
    import os
    import weechat
    import logging
    logging.basicConfig(level=logging.ERROR)
    from gntp.notifier import GrowlNotifier
    IMPORT_OK = True
except ImportError as error:
    IMPORT_OK = False
    if str(error).find('weechat') != -1:
        print('This script must be run under WeeChat.')
        print('Get WeeChat at http://www.weechat.org.')
    elif str(error).find('notifier') != -1:
        weechat.prnt('', 'growl: GNTP bindings are not installed')
    else:
        weechat.prnt('', 'growl: {0}'.format(error))
```

![Screenshot](http://d1zjcuqflbd5k.cloudfront.net/files/acc_55771/nLZ?response-content-disposition=inline;%20filename=Screenshot%20on%202013-06-13%20at%2013.22.37.png;%20filename*=UTF-8%27%27Screenshot%20on%202013-06-13%20at%2013.22.37.png&Expires=1371155052&Signature=ZW1aGLMEhFiRPNuIQjweb5ps6~rsS5B1KUkwUS0Yon0wntHzVUNyfagRNGMPWPtEvL26FVlkdT2wgb4BZxh8q9PFcYKISnDPVxO4rPCbulFeuF7elkYSk3kab58-qaG5mKlaWlCKMxxdPzwUG-simSIuOU87aVkgCyDZWxDC5XI_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)

**Comment by sorin-ionescu** [comment]
You're screenshots don't work.

**Comment by ewilliam** [comment]
oh, sorry. the error was:

python: stdout/stderr: ERROR:gntp.notifier:Invalid response: (u'400', u'There was an error parsing the key for validity')

**Comment by sorin-ionescu** [comment]
It's probably something wrong with the GNTP notification. I apologise, but I do not have an answer.
